Taras vasylychyn
tatomyr/__oop-2023--it-31 pull request #5
Opened 2023-02-15 13:18 UTC by pettrichor

2023-02-22 08:18 UTC, tatomyr commented on Taras_Vasylychyn/lab_2/lab-2.md
> +Звіт про виконання лабораторної роботи №2
```suggestion
# Звіт 
#### про виконання лабораторної роботи №2
```

2023-02-22 08:18 UTC, tatomyr commented on Taras_Vasylychyn/lab_2/lab-2.md
> +"Variables and Types, Lists, Basic Operators, String Formatting, Basic String Operations, Dictionaries"
```suggestion
### "Variables and Types, Lists, Basic Operators, String Formatting, Basic String Operations, Dictionaries"
```

2023-03-01 07:20 UTC, tatomyr commented on Taras_Vasylychyn/README.md
> +[Практична робота №3](./lab_3/lab_3.py)
```suggestion
[Практична робота №1](./lab_1/lab-1.md)
[Практична робота №2](./lab_2/lab-2.md)
[Практична робота №3](./lab_3/lab_3.md)
```

2023-03-01 07:22 UTC, tatomyr commented on Taras_Vasylychyn/lab_1/lab-1.md
> +### Звіт про виконання лабораторної роботи №1
```suggestion
# Звіт про виконання лабораторної роботи №1
```

2023-03-01 07:22 UTC, tatomyr commented on Taras_Vasylychyn/lab_1/lab-1.md
> +### "Ознайомлення з Python, GitHub"
```suggestion
### Звіт про виконання лабораторної роботи №1
# "Ознайомлення з Python, GitHub"
```

2023-03-01 07:23 UTC, tatomyr commented on Taras_Vasylychyn/lab_2/lab-2.md
> +### "Ознайомлення з Python, GitHub"
A wrong theme perhaps?

2023-03-01 07:23 UTC, tatomyr commented on Taras_Vasylychyn/lab_2/lab-2.md
> +### Звіт про виконання лабораторної роботи №1
2?

2023-03-01 07:24 UTC, tatomyr commented on Taras_Vasylychyn/lab_1/lab-1.md
> +#### надсилати програму до репозиторії на GitHub, щоб викладач міг ознайомитися з кодом.
```suggestion
## Висновки. 

На даній лабораторній роботі я познайомився з основами мови програмування Python, також навчився надсилати програму до репозиторії на GitHub, щоб викладач міг ознайомитися з кодом. 
```

2023-03-01 07:25 UTC, tatomyr commented on Taras_Vasylychyn/lab_1/lab-1.md
> +10. Заходжу на GitHub і натискаю "pull request".
Link to your code, repo...

2023-03-01 07:30 UTC, tatomyr requested changes
Please make changes to all documents according to my suggestions.

2023-03-08 07:39 UTC, tatomyr commented on Taras_Vasylychyn/lab-5/lab-5.md
> +Клас на Python - це сукупність об’єктів, ми можемо сприймати клас як план, ескіз чи прототип. Він містить усі деталі об’єкта.
Не зовсім!

2023-03-08 07:44 UTC, pettrichor commented on Taras_Vasylychyn/lab-5/lab-5.md
> +print(sum)
```suggestion
class MyClass: 
     a = 10 
     b = 20    
     def add(): 
     sum = a+b 
     print(sum)
```

2023-03-08 07:47 UTC, pettrichor commented on Taras_Vasylychyn/lab-5/lab-5.md
> +```
```suggestion
class MyClass: 
     a = 10 
     b = 20    
     def add(): 
        sum = a+b 
        print(sum)
```
```

2023-03-08 08:08 UTC, tatomyr approved these changes

2023-03-08 08:08 UTC, merged